### ISSUE TITLE
Requested features for new plotting scripts

### ISSUE THREAD

**Issue by JanvanderLinden** [kit-cn-cms/pyroot-plotscripts#11]
The following features have been requested for the new plotting routines:

- [x] easier way to generate shape plots by just adding a flag to the top level scripts that handle everything in the backend. If this option is activated, there should be no need for `data_obs` histograms in the root file

- [x] correlated to (1) there should be an option like `data` for plotting, where adding the `data_obs` histogram is made optional. This should of course also disable data/MC ratio plots.

- [x] an ordered list to adjust the order of samples in the stacked backgrounds (should exist in the `pltcfg_X.py` files and be written to the local `plotconfig.py`)

**Comment by michaelwassmer** [comment]
In addition, the possibility to scale the textsize of the category labels would be really nice since large labels extend over the pad currently.
