### ISSUE TITLE
parallelize mergeSystematics step

### ISSUE THREAD

**Issue by pkausw** [kit-cn-cms/pyroot-plotscripts#23]
This becomes paramount when analyzing multiple observables at once. Definitely need to do this for the 2D input feature validation!

Probably done best after hadding the different processes. Need to
- map input file to given process and use current .sh script generation or rewrite python script that calls `combine_intermed_syst.py` so it doesn't load a process anymore
- check that monitoring is working with new structure

**Comment by sebwieland** [comment]
I can take a look at it.
