### ISSUE TITLE
need logic to reduce number of histograms to fill in cc file

### ISSUE THREAD

**Issue by pkausw** [kit-cn-cms/pyroot-plotscripts#27]
It often happens that the number of histograms to produce in one plotscript run becomes very large. Of course, this also means that the runtime increases, resulting in jobs that will never be submitted by the scheduler or in the need to optimize the requested runtime for a given job by trial and error.

Maybe it would be better to somehow introduce an upper limit to the number of histograms to be produced per job (which should be set-able). The easiest way for sure would be to write a script which generates multiple configs that can be used in multiple plotscript runs.

A nicer way might be to actually split the histogram definitions and the logic to fill them into separate files (maybe define class?) and then to just give this file to the main cc file which can then just call some externally defined functions.

Any comments or ideas are highly welcome!

**Comment by pkausw** [comment]
Has anybody started with this? :D Might be interesting for the 2D validation :grimacing:

**Comment by sebwieland** [comment]
Not Yet.
I'm performing various other optimizations right now concerning the runtime.
Most importanly one can save ~80% of runtime, when loading the MEM from FriendTrees, which I am creating right now.
Nonetheless, the proposed feature should be a nice addon to the plotscript in general.

**Comment by sebwieland** [comment]
I started outsourcing some plot Stuff into a separate class.
Unfortunately the runtime increases by ~60% =((( [Branch](https://github.com/kit-cn-cms/pyroot-plotscripts/tree/theRealLegacyAnalysis_factorizePlots)
