### ISSUE TITLE
mergeSysts

### ISSUE THREAD

**Issue by sebwieland** [kit-cn-cms/pyroot-plotscripts#30]
Would be nice to skip the mergeSysts step, when it's not neccessary.
Therefore, some logic is needed to detect if a pdf systematic is present in the systs.csv

**Comment by pkausw** [comment]
Isn't this (*) exactly that?

(*) https://github.com/kit-cn-cms/pyroot-plotscripts/blob/61b1fc2325fb8ad7252ddf9b829b0649afc48da8/plottingscripts/inputFeatures_final_2016.py#L239

**Comment by sebwieland** [comment]
Ah I see. Yes this works ;)
Although It would be even nicer to automatically detect if mergeSysts Step is needed (?)

**Comment by pkausw** [comment]
Puh, I think that might be a little more/too complicated since that information resides in the systematics object, which currently doesn't communicate with the top level script/the plotParallel class

**Comment by sebwieland** [comment]
Okay, then let's close this Issue and keep it in the back of our minds for future ourselves ;)
